server:
  port: 8282
spring:
  datasource:
    url: <DB_CONNECTION_STRING>#jdbc:h2:mem:testdb
    username: <DB_USERNAME>
    password: <DB_PASSWORD>
    driver-class-name: com.mysql.cj.jdbc.Driver #org.h2.Driver
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: 'update'
  h2:
    console:
      enabled: true  # Enable Access to H2 client Console http://localhost:8181/h2-console/login.jsp